- configs/zuerich.yaml
- Move `buses_use_synthetic_diesel` to subaction of `improved_vehicle_fleet`
- Add updated `heater_replacement_and_district_heat` and subaction content
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205805031547381
- https://app.asana.com/0/0/1205727549456420
> Zuerich: Update action content

- paths/settings.py
RichText embeds: added setting WAGTAILEMBEDS_RESPONSIVE_HTML for responsive object class. 
Similar to https://github.com/kausaltech/kausal-watch-private/pull/57
> Added wagtail embed settings for responsive objects

- configs/espoo.yaml
- configs/frameworks/hsy.yaml
- nodes/actions/simple.py
- nodes/simple.py
- paths/graphql_helpers.py
I need to update Espoo datasets but I keep getting mysterious errors  locally both with UI and terminal. Who can help me out?
> Add ScenarioAction. Update Espoo dataset

- configs/c4cdemo.yaml
- configs/frameworks/buildings_nzc.yaml
- configs/frameworks/transport_nzc.yaml
- configs/nzc.yaml
- configs/surrey.yaml
- configs/tampere.yaml
- datasets/management/commands/store_dvc_dataset.py
- datasets/models.py
- nodes/actions/gpc.py
- nodes/apps.py
- nodes/gpc.py
- nodes/node.py
- nodes/signals.py
- notebooks/C4C-Dataset-Actions.py
- notebooks/C4C-Dataset-Baseline.py
- params/global_params.py
- paths/settings.py
I glanced at the commits here and it should be safe to merge main into production-lagecy.
> Updates for Tampere datasets & other stuff

- pages/sitecontent.py
I noticed some issues with the modeladmin migration I did to the `InstanceSiteContentViewSet` a while ago, here are the fixes.
> Sitecontent migration afterthought

- configs/potsdam-gpc.yaml
- nodes/actions/gpc.py
Fixes issues with Potsdam energy consumption actions.
> Fix Potsdam calculation errors

- admin_site/wagtail_hooks.py
- datasets/management/commands/load_dvc_dataset.py
- datasets/management/commands/store_dvc_dataset.py
- nodes/models.py
- paths/middleware.py
Recent changes has broken some references, this PR fixes some I stumbled upon.
> Fix broken references

- configs/nzc.yaml
- nodes/instance.py
Allows us to show a prompt on the frontend to refresh the page if data may have changed for NetZeroPlanner instances.
https://app.asana.com/0/1206017643443542/1208538543650805/f
> Add instance feature flag to encourage page refresh when data is stale

- configs/potsdam-gpc.yaml
Fixes
- https://app.asana.com/0/1206017643443542/1208909507644129/f
- https://app.asana.com/0/1206017643443542/1208909507644132/f
> Potsdam model updates

- configs/dut-transport-nzc.yaml
- configs/frameworks/health.yaml
- configs/greentransition.yaml
- configs/lappeenranta-nzc.yaml
- configs/lappeenranta-syke.yaml
- configs/modules/health.yaml
- configs/nzc.yaml
- configs/nzc/electricity.yaml
- configs/nzc/freight_transport.yaml
- configs/nzc/transport.yaml
- nodes/actions/action.py
- nodes/actions/gpc.py
- nodes/constants.py
- nodes/gpc.py
- nodes/health_impact_units.txt
- nodes/instance_loader.py
- nodes/metric_gen.py
- nodes/node.py
- nodes/simple.py
- nodes/units.py
This should be merged into main before feature/probability2.
> Add value of information to compute_indicator()

- admin_site/templates/wagtailadmin/home.html
After merging, needs to be translated ASAP into all languages.
> Greet users by name

- admin_site/wagtail_hooks.py
See also:
- https://github.com/kausaltech/kausal-extensions/pull/73
- https://github.com/kausaltech/kausal-backend-common/pull/12
> Use dataset schema view set

- admin_site/dataset_admin.py
- admin_site/wagtail_hooks.py
- paths/dataset_config.py
This will help in adding the permission policy
Also add some configuration variables soon to be used
> Move DatasetSchemaViewSet from kausal_common to paths

- admin_site/dataset_admin.py
- paths/dataset_config.py
But only if configured with SCHEMA_HAS_SINGLE_DATASET
> Redirect user to dataset edit view after creating schema

- nodes/models.py
Sync dimensions and categories from nodes to datasets
> Common datasets sync_dimensions and sync_categories

- conftest.py
- paths/apps.py
- paths/settings.py
- users/forms.py
- users/templates/users/create.html
- users/templates/users/edit.html
- users/tests.py
- users/tests/test_login.py
- users/viewsets.py
This seemingly small change requires a lot of work like customizing templates and views.
I wanted to write more tests for this, but this would be a bigger undertaking.
[Asana task](https://app.asana.com/0/1206017643443542/1209127093898700)
> Add is_staff field to user create/edit form

- admin_site/dataset_admin.py
fixes [DSBUG-27](https://app.asana.com/1/1201243246741462/project/1209669883307376/task/1209678386115181)
> Filter schema viewset dimension chooser by scope

- admin_site/dataset_admin.py
- admin_site/viewsets.py
- admin_site/wagtail_hooks.py
See common PR: https://github.com/kausaltech/kausal-backend-common/pull/27
> [DSBUG-22] Hide snippets menu

- configs/aarhus-c4c.yaml
- configs/bytom-c4c.yaml
- configs/longmont.yaml
- configs/ostersund-c4c.yaml
- configs/riga-c4c.yaml
- configs/saskatoon.yaml
- configs/surrey.yaml
- configs/tampere-c4c.yaml
- configs/zuerich-dev.yaml
- configs/zuerich.yaml
Add db dataset feature flags to the first batch of instances.
> Add db dataset feature flags

- paths/dataset_config.py
- paths/dataset_permission_policy.py
- paths/types.py
Still a bit WIP, but please review and leave comments.
Relies on [kausal-backend-common PR](https://github.com/kausaltech/kausal-backend-common/pull/32). I pushed with `--no-verify` because that one is not on `main` yet.
> Use permission policies in datasets REST API

- configs/nzc.yaml
- configs/nzc/buildings.yaml
- nodes/gpc.py
Some bugfixes for NetZeroPlanner
> Fix reference year observations and "ghost data"

- common/polars.py
- common/polars_ext.py
- configs/espoo.yaml
- configs/longmont-dev.yaml
- frameworks/datasets.py
- nodes/context.py
- nodes/datasets.py
- nodes/metric.py
- nodes/metric_gen.py
- nodes/node.py
- nodes/visualizations.py
- notebooks/optimize.ipynb
The critical thing to check: MetricData.values and DimensionalMetric.values now allow None in the list. Does this cause any systemic problems?
> Fix the progress tracker with observed years
